---
- name: stop the mailhog service
  ansible.builtin.service:
    name: mailhog
    state: stopped

- name: disable the mailhog service
  community.general.sysrc:
    name: mailhog_enable
    value: "NO"

- name: remove mailhog config
  ansible.builtin.file:
    path: /usr/local/etc/rc.conf.d/mailhog
    state: absent

- name: remove mailhog nginx config
  ansible.builtin.file:
    path: "{{ nginx.prefix.config }}/http.d/mailhog.conf"
    state: absent
